name: deploy_firebase_hosting
on:
  push:
    branches:
      - master
jobs:
  deploy_firebase_hosting:
    runs-on: macos-latest
    steps:
      - name: cd
        run: cd docs

      - name: Deploy to Firebase
        run: firebase deploy --token=$1//0e920RYX9hLwNCgYIARAAGA4SNwF-L9IrrjhCsQSRJusPo1JvEXk1nP9XRXh1Qzru6usD7rNqjQR6JCrtwFP0dYcHbMBkcSmmoZ8
